### ISSUE TITLE
[Bug]: Domain bounds

### ISSUE THREAD

**Issue by GiuseppeOrlando878776** [hpc-maths/samurai#251]
### What happened?

There are some problems when the ratio between the length and the height of a domain is not an integer. An exceeding bound is observed and, moreover, a significant high number of elements on zero levels appears.
<img width="635" alt="rectangular_domain" src="https://github.com/user-attachments/assets/c14c47a2-e160-4651-9a63-fe8d9ebee5fa" />

### Input code

```cpp
xt::xtensor_fixed<double, xt::xshape<2>> min_corner = {0.0,0.0};
xt::xtensor_fixed<double, xt::xshape<2>> max_corner = {0.8, 1.61};
samurai::Box<double, dim> box(min_corner, max_corner);
```

### What expected?

The domain should by (0,0.8) x (0,1.61), but when visualized a domain (0,0.8) x (0,1.65). Moreover, imposing on level 0 there are already 528 elements.

### What is your operating system?

Mac OS

### How did you install our software?

conda or mamba

### Software version

0.19.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pmatalon** [comment]
samurai has the following constraint: the domain must be identically represented at every level, including the level 0. This means that samurai tries to find a correct cell length to cover the box at level 0. The other levels are just refinement of that initial level.
What samurai does NOT do (at this point) is refine the mesh to approximate the boundary.

Here, since the width is not a multiple of the height (or conversely), the domain cannot be exactly represented by square elements. It can only be approximated up to a certain tolerance. The smaller the elements, the better the approximation of your box.
Here is what samurai does in this case: the first *tentative length* for the element is the smallest side of the box (here the width: 0.8). Then, this element is successively refined in order to approximate the other side (here the height: 1.61). It does so until that side is approximated up to a tolerance of 5%.
That tolerance can be changed this way:
```cpp
double tol = 0.1; // 10%
samurai::MRMesh<...> mesh(box, min_level, max_level, tol);
```
If you do not want this behaviour, you can directly set the cell length at level 0:
```cpp
double tol = 0.1; // unused
double cell_length_level0 = 0.1;
samurai::MRMesh<...> mesh(box, min_level, max_level, tol, cell_length_level0);
```
However, if you do that, both sides might be approximated. With the tolerance, at least one side is exact.
